spring:
  port: 8080
  application:
    name: mina-usermanagement-svc
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/mina_user_management}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:qwerty}
  main:
    allow-circular-references: true
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8090/realms/alamisharia
#          jwk-set-uri: http://localhost:8090/realms/alamisharia/protocol/openid-connect/certs
  dbcp2:
    max-wait-millis: 30000
    validation-query: SELECT 1
    validation-query-timeout: 30
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
  keycloak:
    admin:
      realm: ${KEYCLOAK_ADMIN_REALM:master}
      username: ${KEYCLOAK_ADMIN_USERNAME:admin}
      password: ${KEYCLOAK_ADMIN_PASSWORD:admin}
      client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:admin-cli}
springdoc:
  pathsToMatch: /api/**
  show-actuator: true
  swagger-ui:
    groups-order: DESC
    disable-swagger-default-url: true

keycloak:
  auth-server-url: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8090}
  realm: ${KEYCLOAK_REALM:alami}
  resource: ${KEYCLOAK_CLIENT_ID:mina-app}
  ssl-required: external
  principal-attribute: preferred_username
  use-resource-role-mappings: true